project_id = "xcvlijchkmhjonhfildm"

[functions.send-order-notification]
verify_jwt = false

[functions.send-order-notification-improved]
verify_jwt = false

[functions.check-promo-alerts]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false
